//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTNhom_MocPhuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public int IDHD { get; set; }
        public string MAKH { get; set; }
        public Nullable<System.DateTime> NGAYDATHANG { get; set; }
        public Nullable<System.DateTime> NGAYGIAOHANG { get; set; }
        public string NOIGIAOHANG { get; set; }
        public string MANVDUYET { get; set; }
        public string MANVGIAO { get; set; }
        public string MAPT { get; set; }
        public string TINHTRANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN1 { get; set; }
        public virtual PHUONGTHUCTT PHUONGTHUCTT { get; set; }
        public virtual TINHTRANG TINHTRANG1 { get; set; }
    }
}
