//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTNhom_MocPhuc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MocPhucEntities : DbContext
    {
        public MocPhucEntities()
            : base("name=MocPhucEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BINHLUAN> BINHLUANs { get; set; }
        public virtual DbSet<CTHD> CTHDs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAISP> LOAISPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHUONGTHUCTT> PHUONGTHUCTTs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<TINHTRANG> TINHTRANGs { get; set; }
    
        public virtual ObjectResult<SP_LAYDANHMUC_SPHAM_Result> SP_LAYDANHMUC_SPHAM(string mALSP)
        {
            var mALSPParameter = mALSP != null ?
                new ObjectParameter("MALSP", mALSP) :
                new ObjectParameter("MALSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LAYDANHMUC_SPHAM_Result>("SP_LAYDANHMUC_SPHAM", mALSPParameter);
        }
    }
}
